// Mirrors the `vendors` table in schema.sql.
// SQLite stores booleans as 0/1 integers, so we convert is_open to a real boolean
// in TypeScript-land — the database representation and the app representation
// don't have to match exactly; that conversion happens in the service layer.

export interface Vendor {
  id: number;
  ownerId: number;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  isOpen: boolean;
  createdAt: string;
}

// Shape required to create a new vendor.
// Notice: no `id` (auto-generated by the DB) and no `createdAt` (DB default).
export interface CreateVendorInput {
  ownerId: number;
  name: string;
  address: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
}

// The raw shape exactly as it comes out of SQLite (snake_case, 0/1 for booleans).
// This type exists so the mapping step (raw → Vendor) is explicit and type-checked.
export interface VendorRow {
  id: number;
  owner_id: number;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  is_open: number;
  created_at: string;
}
